# Generated by Django 5.2 on 2025-04-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="airport.airplane",
            ),
            preserve_default=False,
        ),
    ]
