# Generated by Django 5.2 on 2025-04-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_flight_airplane"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crew",
            old_name="firt_name",
            new_name="first_name",
        ),
    ]
