# Generated by Django 5.2 on 2025-04-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_rename_firt_name_crew_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.IntegerField(
                choices=[
                    (1, "A"),
                    (2, "B"),
                    (3, "C"),
                    (4, "D"),
                    (5, "E"),
                    (6, "F"),
                    (7, "G"),
                    (8, "H"),
                    (9, "I"),
                    (10, "J"),
                ]
            ),
        ),
    ]
