# Generated by Django 5.2 on 2025-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                db_index=True, related_name="flights", to="airport.crew"
            ),
        ),
    ]
