# Generated by Django 5.2 on 2025-05-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_alter_flight_crew"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Coutry",
            new_name="Country",
        ),
        migrations.RenameField(
            model_name="route",
            old_name="sourse",
            new_name="source",
        ),
    ]
